### PR TITLE
Perk Balancing (based on pickrate)

### PR DESCRIPTION
**Pull request by Draze22**
• Cast Range perks: 
    - Decreased cast range from 50/100/200/400 to 45/90/180/360
• Cooldown Reduction perks: 
    - Decreased cooldown reduction from 4/8/16/32% to 4/8/15/25%
• Builder perks: 
    - Increased bonus healing from 5/10/20/40 to 15/30/60/120
    - Improved fequency from every 30s to every 15s
• Linkens perks: 
    - Iincreased buff duration from 3/4/5/6 to 7/7/7/7 
    - Rescaled cast range from 400/550/700/900 to 700/700/700/700
• Evasion perks: 
    - Increased evasion from 7/14/28/56% to 15/25/40/60%
• Delayed Damage perks: 
    - Rescaled damage reduction from 8/16/32/64% to 15/25/40/60%
    - Rescaled delay duration from 5/8/10/12s to 10/10/10/10s
• Health perks: 
    - Increased bonus health from 5/10/20/40% to 10/20/40/80%
• Healing Amplify perks: 
    - Increased bonus healing from 8/16/32/64% to 10/20/40/80%
• Magic Resistance perks: 
    - Rescaled magic resistance from 7/14/28/56% to 10/20/35/50%
• Combat Readiness perks: 
    - Increased cooldown restored after death from 25/50/75/100% to 40/60/80/100%
• Manaburn perks: 
    - Increased mana burnt from 8/16/32/64 to 10/20/40/80
• Lifesteal perks: 
    - Increased lifesteal from 5/10/20/40 to 8/16/32/64
• Spell Lifesteal perks: 
    - Increased spell lifesteal from 3/6/12/24 to 5/10/20/40 
    - Reduced spell lifesteal from creeps from 50% to 20% of spell lifesteal from heroes
• Health Regen perks: 
    - Rescaled base regen from 3/2.5/2/4 to 1.5/3/6/12 
    - Buffed regen per level from 0/0.5/1/2 to 0.25/0.5/1/2
• Mana Regen perks: 
    - Rescaled base regen from 1.5/1/2/4 to 0.75/1.5/3/6 
    - Buffed regen per level from 0/0.2/0.4/0.8 to 0.1/0.2/0.4/0.8
• Movement Speed perks: 
    - Increased bonus movement speed from 10/20/40/80 to 15/30/60/120
• Status Resistance perks: 
    - Rescaled status resistance from 9/18/36/72% to 15/25/40/60%
• Attack Range perks: 
    - Increased melee attack range from 25/50/100/150 to 30/60/120/240

### CODE REVIEW

**Comment by AustraliaIsMyCity** [comment]
Builder perk should have its frequency dropped to 10 seconds on top of current buffs, then it effectively gives 1.5, 3, 6, 12 hp regen which is potentially almost enough to be decent

id also like to see the melee bonus attack range increased to maybe 75% of the ranged counterpart, its currently extremely underwhelming.

**Comment by Draze22** [comment]
Dropped Builder's frequency to 15s instead of 10s and increased melee Attack Range as requested.

**Comment by AustraliaIsMyCity** [comment]
LGTM

**Comment by Draze22** [comment]
Got a few tooltips to change first.

**Comment by fcalife** [comment]
I know no one asked but IMO:

> • Evasion perks:
> - Increased evasion from 7/14/28/56% to 15/25/40/60%
> • Delayed Damage perks:
> - Rescaled damage reduction from 8/16/32/64% to 15/25/40/60%
> • Status Resistance perks:
> - Rescaled status resistance from 9/18/36/72% to 15/25/40/60%

How about 10/20/40/60% for those?

> • Mage perks:
> - Rescaled intelligence per kill from 1/2/4/8 to 1.2/2.4/3.6/4.8

How about 1/2/4/6? or 1.25/2.5/4/6?

**Comment by Draze22** [comment]
> How about 10/20/40/60% for those?

15/25/40/60% makes them gives each tier roughly double the effective hp of the previous tier without straying from multiples of 5.

> How about 1/2/4/6? or 1.25/2.5/4/6?

I looked at the stats again and there's no real reason to change it from 1/2/4/8, I'm going to revert it.

**Comment by fcalife** [comment]
15% at level 1 is too strong though. Not 2 months ago those perks had numbers like 6 or 7% at level 1.

**Comment by Draze22** [comment]
> 15% at level 1 is too strong though. Not 2 months ago those perks had numbers like 6 or 7% at level 1.

None of these stats are highly valuable in 12v12. Most of the game is farming quickly, avoiding getting hit by spells or attack in the first place or bening useful at the same time. In 5v5 these buffs would be too strong but in 12v12 they won't be.

**Comment by fcalife** [comment]
Ok

**Comment by Draze22** [comment]
For reference Evasion has been the third least picked ability over the last 3 months with a 0.3% pickrate (average perk pickrate is 3%).

**Pull request merged**
